# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name Rcpp Object for conducting Joint Mirror Procedure.
#' @title Rcpp Object for conducting Joint Mirror Procedure.
NULL

